@Server_HostAddress = http://localhost:5264

GET {{Server_HostAddress}}/api/user/1
Accept: application/json

###


GET {{Server_HostAddress}}/api/feed?username=brandonchastain@gmail.com
Accept: application/json

###


GET {{Server_HostAddress}}/api/item/timeline?username=brandonchastain@gmail.com
Accept: application/json